# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 飞龙 Francis
description: > # this means to ignore newlines until "baseurl:"
  Focus on database, web technology, and general topics about computer programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flniu.github.io" # the base hostname & protocol for your site
repository: "flniu/flniu.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Personal information
my:
  name: 牛飞龙 | Francis Niu
  location: 西安 | Xi'an
  job:
  school: 华东师范大学 计算机 本科 | ECNU CS Bachelor
  website: https://flniu.github.io
  githubid: flniu
  linkedinid:
  twitterid:
  email: echo flniu%126.com | tr % @
  weixin: feilongsss
  phone:
  skillList:
    - skill: Database/SQL
      percentage: 90%
    - skill: VLDB
      percentage: 50%
    - skill: BigData
      percentage: 30%
    - skill: NoSQL
      percentage: 10%
    - skill: BI(DW/ETL/Reporting)
      percentage: 70%
    - skill: .NET
      percentage: 70%
    - skill: Python
      percentage: 60%
    - skill: HTML/CSS/JS
      percentage: 60%
    - skill: Web Analysis
      percentage: 60%
    - skill: Vim
      percentage: 80%

