# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: F.IT笔记
description: > # this means to ignore newlines until "baseurl:"
  database, programming, education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flniu.github.io" # the base hostname & protocol for your site
repository: "flniu/flniu.github.io"
img: "https://oic6jgqb8.qnssl.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
timezone: Asia/Shanghai
paginate: 20

# Set defaults for YAML Front Matter variables
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      category: blog

# Personal information
my:
  name: Francis Niu
  location: Xi'an, China
  job:
  school: ECNU CS Bachelor
  website: https://flniu.github.io
  githubid: flniu
  linkedinid:
  twitterid:
  email: echo flniu%126.com | tr % @
  weixin: feilongsss
  phone:
  skillList:
    - skill: Database/VLDB/BI
      percentage: 90%
    - skill: BigData/NoSQL/NewSQL
      percentage: 20%
    - skill: Python
      percentage: 80%
    - skill: HTML/CSS/JS
      percentage: 60%
    - skill: Vim
      percentage: 80%

