# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 牛飞龙 | Francis Niu
#email: flniu@126.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog which mainly focuses on database, big-data, cloud-computing,
  and general topics about computer programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flniu.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  flniu

# Build settings
markdown: kramdown
permalink: pretty

# Personal information
my:
  name: 牛飞龙 | Francis Niu
  location: 西安 | Xi'an
  skillList:
    - skill: SQL/ETL
      percentage: 100%
    - skill: VLDB
      percentage: 50%
    - skill: BigData
      percentage: 20%
    - skill: NoSQL
      percentage: 10%
    - skill: .NET
      percentage: 70%
    - skill: Python
      percentage: 60%
    - skill: HTML/CSS/JS
      percentage: 60%
    - skill: Vim
      percentage: 80%

