#!/bin/bash

if [ "$#" -lt 2 ] || [[ ! "$1" =~ ^(post|wiki)$ ]]; then
  echo "$0 {post|wiki} file_name"
  exit
fi

file_type=$1
shift

file_name=$*
file_name=$(echo "$file_name" | tr [A-Z] [a-z])
file_name=${file_name// /-}
if [ "$file_type" = "post" ]; then
  file_name=_posts/$(date +"%Y-%m-%d")-$file_name.md
else
  file_name=wiki/$file_name.md
fi

echo "new: $file_name"
gvim -c "0r _templates/${file_type}.md" -c "%s/date: \zs/\=strftime('%Y-%m-%d %H:%M:%S')/" $file_name
